Repository monho/emoji, pull requests merged in 2025-04, with the labels that each got.

#10 [MainPage] ui 구현 완료
  assets/image/question_mark.png
  assets/lottie/emoji.json
  assets/lottie/loading.json
  assets/lottie/radar.json
  lib/main.dart
  lib/view/main/main_page.dart
  pubspec.lock
  pubspec.yaml
Labels: feat

#7 [ChatRoom]채팅방 레이아웃 작업 완료
  lib/main.dart
  lib/view/chatroom/chatroom_view.dart
Labels: feat

#14 [Terms]약관동의 페이지 UI구현
  lib/main.dart
  lib/terms/terms_screen.dart
  lib/view/splash/splash_screen.dart
  pubspec.lock
  pubspec.yaml
Labels: feat

#16 [ChatRoom] 채팅방 UI 구현 및 파이어베이스 기본연동 완료
  android/app/build.gradle.kts
  android/app/google-services.json
  android/settings.gradle.kts
  firebase.json
  lib/core/chat_provider.dart
  lib/firebase_options.dart
  lib/main.dart
  lib/model/chatroom/chatroom_model.dart
  lib/view/chatroom/chatroom_view.dart
  lib/viewmodel/chatroom/chatroom_viewmodel.dart
  macos/Flutter/GeneratedPluginRegistrant.swift
  pubspec.lock
  pubspec.yaml
  windows/flutter/generated_plugin_registrant.cc
  windows/flutter/generated_plugins.cmake
Labels: feat

#21 [Core] 디바이스 아이디 수집 기능 완료
  lib/main.dart
  lib/model/user/user_model.dart
  lib/repository/user_repository.dart
  lib/view/main/main_page.dart
  lib/viewmodel/code/code_viewmodel.dart
  lib/viewmodel/user/user_viewmodel.dart
  macos/Flutter/GeneratedPluginRegistrant.swift
  pubspec.lock
  pubspec.yaml
Labels: feat

#25 [ChatRoom] 이모티콘 기능 추가 및 Provider -> Riverpod 으로 방식변경
  assets/emoji/CommentImage
  assets/image/original_m_tab_on_0.png
  assets/image/original_m_tab_on_1.png
  assets/image/original_m_tab_on_2.png
  assets/image/original_m_tab_on_3.png
  assets/image/original_m_tab_on_4.png
  assets/image/original_m_tab_on_5.png
  lib/main.dart
  lib/model/chatroom/chatroom_model.dart
  lib/view/chatroom/chatroom_view.dart
  lib/view/splash/splash_screen.dart
  lib/viewmodel/chatroom/chatroom_viewmodel.dart
  pubspec.lock
  pubspec.yaml
Labels: feat, fix

#28 [Splash] 스플래시 애니메이션 적용
  assets/image/blank_ball.png
  assets/image/splash_kiss.png
  assets/image/splash_smile.png
  assets/image/splash_sunglasses.png
  assets/image/splash_wink.png
  devtools_options.yaml
  lib/main.dart
  lib/view/splash/splash_screen.dart
Labels: fix

#30 [Splash] 머지 이슈 해결
  lib/view/splash/splash_screen.dart
Labels: fix
